# Generated by Django 4.1.4 on 2022-12-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
