# Generated by Django 4.1.4 on 2022-12-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_user_address_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/app1'),
        ),
    ]
